language: python

python:
  - "3.6"
  - "3.7"

cache: pip

install:
  - pip install virtualenv
  - virtualenv twit_ci
  - source twit_ci/bin/activate
  - pip install -r requirements.txt

before_script:
  - source twit_ci/bin/activate

script:
  - travis_retry behave

deploy:
  # Static Assets
  - provider: s3
    on:
      branch: master
      python: "3.6"
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: cdn.twitkov.club
    skip_cleanup: true
    local_dir: ./static
    cache_control: "max-age=21600"
  # API
  - provider: script
    skip_cleanup: true
    on:
      branch: master
      python: "3.6"
    script: "cd $TRAVIS_BUILD_DIR && chmod +x ./deploy.sh && ./deploy.sh"
