name: Production Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    uses: ./.github/workflows/deploy.yml
    permissions:
      id-token: write
      contents: read
      packages: write
    needs:
      - test
    with:
      aws_region: us-east-2
      aws_role: arn:aws:iam::845666362991:role/us-east-2-tmm-bluto-github
      environment: production
