name: Test

on: [workflow_call]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache-dependency-path: |
            requirements/*.txt

      - name: Install dependencies
        run: pip install -r requirements/dev.txt

      - name: Check format/lint
        working-directory: svcs/transcriber
        run: ruff check
